---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: it-tools-external
    namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
  - name: external
    namespace: istio-gateway
  hostnames:
    - "it-tools.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: it-tools
      port: {{ .Values.ittools.port }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: it-tools-internal
    namespace: {{ $.Release.Namespace }}
    annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Usefull tools for IT professionals
        gethomepage.dev/group: Tools
        gethomepage.dev/icon: it-tools
        gethomepage.dev/name: IT Tools
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "it-tools.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: it-tools
      port: {{ .Values.ittools.port }}
