---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: linkwarden-internal
    namespace: {{ $.Release.Namespace }}
    annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Bookmarks
        gethomepage.dev/group: Knowledge
        gethomepage.dev/icon: linkwarden
        gethomepage.dev/name: Linkwarden
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "linkwarden.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: linkwarden
      port: {{ .Values.linkwarden.port }}
