---
changedetection:
    image: dgtlmoon/changedetection.io:0.48.03
    port: 5000
    baseUrl: changedetection.stefangenov.site
    resources:
        requests:
            cpu: 10m
            memory: 125Mi
    selenium:
        image: selenium/standalone-chrome-debug:3.141.59
        port: 4444
    playwright:
        image: browserless/chrome:1.61-chrome-stable
        port: 3000

storage:
    configSize: 1Gi
