---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: n8n-internal
    namespace: {{ $.Release.Namespace }}
    annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Low-code automation
        gethomepage.dev/group: Automation
        gethomepage.dev/icon: n8n
        gethomepage.dev/name: N8N
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "n8n.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: n8n
      port: {{ .Values.n8n.port }}
