---
nodered:
    image: nodered/node-red:3.1.0-16
    port: 1880
    resources:
        requests:
            cpu: 250m
            memory: 512Mi
        limits:
            memory: 2Gi
storage:
    dataLocality: best-effort
    numberOfReplicas: 1
    configSize: 5Gi
    nasIp: 192.168.1.20
