---
apiVersion: v2
appVersion: 1.0.0
description: This chart is used to install pyload
maintainers:
    - email: sgenov94@gmail.com
      name: Stefan Genov
name: pyload
type: application
version: 2.0.0
