apiVersion: v2
appVersion: 1.0.0
description: This chart is used to install whoogle
maintainers:
- email: sgenov94@gmail.com
  name: Stefan Genov
name: whoogle
type: application
version: 1.0.0
