---
apiVersion: v2
appVersion: 1.0.0
description: This chart is used to install homebox
maintainers:
  - email: sgenov94@gmail.com
    name: Stefan Genov
name: homebox
type: application
version: 2.0.0
