---
n8n:
    image: n8nio/n8n:1.60.0
    port: 5678
    replicas: 1
    resources:
        requests:
            cpu: 10m
            memory: 250Mi

postgres:
    image: postgres:16.4
    dataSize: 2Gi
    port: 5432
    resources:
        requests:
            cpu: 10m
            memory: 256Mi

