---
storage:
    transmission:
        config: 1Gi
        downloads: 200Gi
    kavita:
        config: 5Gi
    overseer:
        config: 5Gi
    radarr:
        config: 5Gi
    sonarr:
        config: 5Gi
    prowlarr:
        config: 10Gi
    readarr:
        config: 5Gi
    doplarr:
        config: 5Gi

flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.16
    port: 8191
    resources:
        requests:
            cpu: 512m
            memory: 1Gi
transmission:
    image: lscr.io/linuxserver/transmission:4.0.5
    port: 9091
    username: username
    password: password
    resources:
        requests:
            cpu: 250m
            memory: 1Gi
prowlarr:
    replicas: 1
    image: ghcr.io/linuxserver/prowlarr:1.13.3
    port: 9696
    resources:
        requests:
            cpu: 500m
            memory: 1Gi

radarr:
    image: ghcr.io/linuxserver/radarr:5.3.6
    port: 7878
    resources:
        requests:
            cpu: 10m
            memory: 50Mi

readarr:
    image: lscr.io/linuxserver/readarr:0.3.21-nightly
    replicas: 1
    port: 8787
    resources:
        requests:
            cpu: 100m
            memory: 500Mi

overseerr:
    image: lscr.io/linuxserver/overseerr:1.33.2
    port: 5055
    replicas: 1
    resources:
        requests:
            cpu: 10m
            memory: 50Mi

sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.2
    port: 8989
    resources:
        requests:
            cpu: 1
            memory: 1Gi
        limits:
            cpu: 2

kavita:
    image: ghcr.io/linuxserver/kavita:0.7.14
    port: 5000
    replicas: 1
    resources:
        requests:
            cpu: 10m
            memory: 50Mi
