---
storage:
    nasIp: 192.168.1.20
    transmission:
        config: 1Gi
        downloads: 200Gi
    kavita:
        config: 5Gi
    overseer:
        config: 5Gi
    radarr:
        config: 5Gi
    sonarr:
        config: 5Gi
    prowlarr:
        config: 10Gi
    readarr:
        config: 5Gi
    doplarr:
        config: 5Gi

transmission:
    image: lscr.io/linuxserver/transmission:4.0.5
    port: 9091
    username: username
    password: password
    resources:
        requests:
            cpu: 250m
            memory: 1Gi
prowlarr:
    replicas: 1
    image: lscr.io/linuxserver/prowlarr:1.10.3-nightly
    port: 9696
    resources:
        requests:
            cpu: 500m
            memory: 1Gi

radarr:
    image: lscr.io/linuxserver/radarr:5.2.3-nightly
    port: 7878
    resources:
        requests:
            cpu: 10m
            memory: 50Mi

readarr:
    image: lscr.io/linuxserver/readarr:0.3.14-nightly
    replicas: 1
    port: 8787
    resources:
        requests:
            cpu: 100m
            memory: 500Mi

overseerr:
    image: lscr.io/linuxserver/overseerr:1.33.2
    port: 5055
    replicas: 1
    resources:
        requests:
            cpu: 10m
            memory: 50Mi

sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.0
    port: 8989
    resources:
        requests:
            cpu: 1
            memory: 1Gi
        limits:
            cpu: 2

kavita:
    image: kizaing/kavita:0.7.8@sha256:48b3c2c07f90feb4641ddb791f96a1bf6e70a2b27da8c8b2ca0cc2c627b91d72
    port: 5000
    replicas: 1
    resources:
        requests:
            cpu: 10m
            memory: 50Mi
