---
collections:
    - name: kubernetes.core
      version: 3.0.0
    - name: community.general
      version: 8.1.0
roles:
    - src: xanmanning.k3s
    - src: michaelpalacce.helm
    - src: michaelpalacce.kubernetes_preflight
