---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: diagrams-internal
    namespace: {{ $.Release.Namespace }}
    annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Make diagrams in your browser
        gethomepage.dev/group: Tools
        gethomepage.dev/icon: draw-io
        gethomepage.dev/name: Diagrams
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "diagrams.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: diagrams
      port: {{ .Values.diagrams.port }}
