---
apiVersion: v2
appVersion: 1.0.0
description: This chart is used to install foldingathome
maintainers:
  - email: sgenov94@gmail.com
    name: Stefan Genov
name: foldingathome
type: application
version: 3.1.0
