---
foldingathome:
  image: lscr.io/linuxserver/foldingathome:8.4.9
  port: 7396
  replicas: 4 # One for each server
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 3
      memory: 1Gi

storage:
  configSize: 1Gi
