apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden
  labels:
    app.kubernetes.io/instance: garden
    app.kubernetes.io/name: garden
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: garden
      app.kubernetes.io/name: garden
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: garden
        app.kubernetes.io/name: garden
    spec:
      restartPolicy: Always
      priorityClassName: critical-priority
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: garden
                    app.kubernetes.io/name: garden
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - name: garden
          image: ghcr.io/michaelpalacce/garden:v4.1.1769964525
          imagePullPolicy: IfNotPresent
          resources: # Initial run requires a few more resources
            limits:
              cpu: 500m
              memory: 51Mi
          ports:
            - name: web
              containerPort: 80
          securityContext:
            capabilities:
              drop:
                - "ALL"
              add:
                - CHOWN
                - SETUID
                - SETGID
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Sofia"
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 10
            tcpSocket:
              port: 80
            timeoutSeconds: 2
          startupProbe:
            failureThreshold: 20
            timeoutSeconds: 2
            tcpSocket:
              port: 80
