apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden
  labels:
    app.kubernetes.io/instance: garden
    app.kubernetes.io/name: garden
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: garden
      app.kubernetes.io/name: garden
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: garden
        app.kubernetes.io/name: garden
    spec:
      restartPolicy: Always
      containers:
        - name: garden
          image: ghcr.io/michaelpalacce/quartz:v2.0.1768050327 # Quartz image is separate for content to allow for updating `quartz` without needing to bump `garden`
          imagePullPolicy: IfNotPresent
          resources: # Initial run requires a few more resources
            limits:
              cpu: 1
              memory: 1Gi
          ports:
            - name: web
              containerPort: 8080
          securityContext:
            capabilities:
              drop:
                - "ALL"
              add:
                - CHOWN
                - SETUID
                - SETGID
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Sofia"
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 10
            tcpSocket:
              port: 8080
            timeoutSeconds: 2
          startupProbe:
            failureThreshold: 20
            timeoutSeconds: 2
            tcpSocket:
              port: 8080
          volumeMounts:
            - name: garden
              mountPath: /usr/src/app/content
      volumes:
        - name: garden
          image:
            reference: ghcr.io/michaelpalacce/garden:v4.1.1768157707
            pullPolicy: IfNotPresent
