---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: freshrss-internal
    namespace: {{ $.Release.Namespace }}
    annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: RSS Reader
        gethomepage.dev/group: Knowledge
        gethomepage.dev/icon: freshrss
        gethomepage.dev/name: Fresh RSS
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "freshrss.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: freshrss
      port: {{ .Values.freshrss.port }}
