---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: whoogle
    namespace: {{ $.Release.Namespace }}
    annotations:
        kubernetes.io/ingress.class: "nginx"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Self-Hosted Google
        gethomepage.dev/group: Security
        gethomepage.dev/icon: whooglesearch
        gethomepage.dev/name: Whoogle
spec:
    tls:
        -   hosts:
                - "*.stefangenov.site"
            secretName: ingress
    rules:
        -   host: whoogle.stefangenov.site
            http:
                paths:
                    -   pathType: Prefix
                        path: "/"
                        backend:
                            service:
                                name: whoogle
                                port:
                                    number: {{ .Values.whoogle.port }}
