---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: website-external
    namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
  - name: external
    namespace: istio-gateway
  hostnames:
    - "sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: website
      port: {{ .Values.website.port }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: website-internal
    namespace: {{ $.Release.Namespace }}
    annotations:
        # nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: My Website
        gethomepage.dev/group: Personal
        gethomepage.dev/icon: https://sgenov.dev/favicon.ico
        gethomepage.dev/name: Website
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "sgenov.dev"
    - "website.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: website
      port: {{ .Values.website.port }}
