---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - reflector
    - ingress-nginx
    - system-upgrade
    - longhorn-system
    - velero
    - cert-manager
    - kured
    - descheduler
    - metallb
