---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-critical
  - reflector
  - system-upgrade
  - longhorn-system
  - velero
  - cert-manager
  - kyverno
  # - kured
  # - trivy
  - descheduler
  - metallb
  - istio
