---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - reflector
    - ingress-nginx
    - kube-vip
    - system-upgrade
    - longhorn-system
    - velero
    - cert-manager
