apiVersion: v1
kind: Service
metadata:
  name: koffan
spec:
  selector:
    app.kubernetes.io/instance: koffan
    app.kubernetes.io/name: koffan
  ports:
    - name: web
      protocol: TCP
      port: 80
