---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: wallabag-external
    namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
  - name: external
    namespace: istio-gateway
  hostnames:
    - "wallabag.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: wallabag
      port: {{ .Values.wallabag.port }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: wallabag-internal
    namespace: {{ $.Release.Namespace }}
    annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Self-Hosted Pocket
        gethomepage.dev/group: Knowledge
        gethomepage.dev/icon: wallabag
        gethomepage.dev/name: Wallabag
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "wallabag.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: wallabag
      port: {{ .Values.wallabag.port }}
