---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: syncthing-internal
    namespace: {{ $.Release.Namespace }}
    annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: File synchronization
        gethomepage.dev/group: Storage
        gethomepage.dev/icon: syncthing
        gethomepage.dev/name: Syncthing
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "syncthing.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: syncthing
      port: {{ .Values.syncthing.port }}
