---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - changedetection
  - cyberchef
  - diagrams
  - firefly
  - freshrss
  - foldingathome
  - go-ddns-controller
  - gotenberg
  - homepage
  - it-tools
  - mazanoke
  - mealie
  - media
  - n8n
  - nodered
  - openbooks
  - observeability
  - reactiveresume
  - koffan
  - tika
  - uptimekuma
  - vikunja
  - website
  - wallabag
  - paperless-ngx
  - homebox
  - storage
