---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adminer
  # - bentopdf https://www.reddit.com/r/selfhosted/s/Rm4v48pOf8
  - cert-manager
  - changedetection
  - cyberchef
  - diagrams
  - firefly
  - freshrss
  - foldingathome
  - garden
  - go-ddns-controller
  - gotenberg
  - homepage
  - it-tools
  - mazanoke
  - mealie
  - media
  - n8n
  - nodered
  - openbooks
  - linkwarden
  - observeability
  - paperless-ngx
  - reactiveresume
  - replacedby
  - koffan
  - storage
  - tika
  - uptimekuma
  - vikunja
  - website
  - homebox
  - networking-toolbox
  # - wallabag
