---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: openbooks-internal
    namespace: {{ $.Release.Namespace }}
    annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: IRC Book Downloader
        gethomepage.dev/group: Media
        gethomepage.dev/icon: https://raw.githubusercontent.com/evan-buss/openbooks/master/server/app/public/favicon-32x32.png
        gethomepage.dev/name: OpenBooks
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "openbooks.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: openbooks
      port: {{ .Values.openbooks.port }}
