---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: vikunja-internal
    namespace: {{ $.Release.Namespace }}
    annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Tasks
        gethomepage.dev/group: Knowledge
        gethomepage.dev/icon: vikunja
        gethomepage.dev/name: Vikunja
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "vikunja.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: vikunja
      port: {{ .Values.vikunja.port }}
