---
{{- $relNamespace := .Release.Namespace -}}

{{- with .Values.nodeExporter }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: node-exporter
    namespace: {{ $relNamespace }}
    labels:
        name: node-exporter
spec:
    selector:
        matchLabels:
            name: node-exporter
    template:
        metadata:
            labels:
                name: node-exporter
            annotations:
                #                Annotations that will make prometheus scrape the pods for metrics
                prometheus.io/scrape: "true"
                prometheus.io/port: "{{ .port }}"
        spec:
      {{- with .tolerations }}
            tolerations:
        {{- range . }}
                -   key: {{ .key }}
                    effect: {{ .effect }}
            {{- if .value }}
                    value: {{ .value }}
            {{- end }}
        {{- end }}
      {{- end }}
            hostPID: true
            hostIPC: true
            hostNetwork: true
            tolerations: 
              - key: "CriticalAddonsOnly"
                operator: "Equal"
                effect: "NoSchedule"
                value:
            containers:
                -   ports:
                        -   containerPort: {{ .port }}
                            protocol: TCP
                    resources:
                        requests:
                            cpu: 10m
                        limits:
                            cpu: 250m
                    securityContext:
                        privileged: true
                    image: {{ .image }}
                    args:
                        - --path.procfs
                        - /host/proc
                        - --path.sysfs
                        - /host/sys
                        - --collector.filesystem.ignored-mount-points
                        - '"^/(sys|proc|dev|host|etc)($|/)"'
                    name: node-exporter
                    volumeMounts:
                        -   name: dev
                            mountPath: /host/dev
                        -   name: proc
                            mountPath: /host/proc
                        -   name: sys
                            mountPath: /host/sys
                        -   name: rootfs
                            mountPath: /rootfs
            volumes:
                -   name: proc
                    hostPath:
                        path: /proc
                -   name: dev
                    hostPath:
                        path: /dev
                -   name: sys
                    hostPath:
                        path: /sys
                -   name: rootfs
                    hostPath:
                        path: /
{{- end }}
