apiVersion: v1
kind: Service
metadata:
  name: bookdownloader
spec:
  selector:
    app.kubernetes.io/instance: bookdownloader
    app.kubernetes.io/name: bookdownloader
  ports:
    - name: web
      protocol: TCP
      port: 8084
