apiVersion: v1
kind: Service
metadata:
  name: shelfmark
spec:
  selector:
    app.kubernetes.io/instance: shelfmark
    app.kubernetes.io/name: shelfmark
  ports:
    - name: web
      protocol: TCP
      port: 8084
