kind: ConfigMap
apiVersion: v1
metadata:
  name: cloudflare-config
  namespace: go-ddns-controller-system
data:
  config: ENC[AES256_GCM,data:ByjuPiSK+tPXtb+UqYPt/BNh0JX6MkOzEFpxKH3ujW0gqLECWvwSqUflV5ovB3g26E5GoWSi5ni3ZGwfZ1nLffj6ITZ3qPm8oEpT/BygRct6PS0l7CBP5NeHQLYhrZYydOZ5t0lTwBp1XiQO194O2HY2KmMiNDReG4cS1zIhDBWXK3dgce5Uw/LEHC9+Kuh0u99cRuHr64xWrE6aCFKOr9Za2BMk7Gd0oMTUVQ3HLltWYMo9nT7ioNoVcLSdblwPVmC+hui+fWKUKm8Ty0xPNOVCStdYo7MdeiCC3s8yr1wuju4cnp37NixRCsN9f62atJ9cLbw69cYNNln+vFP5mkgUTwndxAXt6iERBhe+xpAZRCIhrCH3rAkGehNCZOwNvoDIYnAOjNBtY4i8CeP5FIIrWKoJmWTvC1dy/CJ6hPkFBTs7H0D38+jatFaij0HgI/+nfeJWa+3RvtlfwMTnSYTrbqqdiD6LEhLeHednJfZAgZdrnc5RYhEHgNbEqZdEQfxl0UfKeu8YC7xgXThWUVDbxuaVdEk533LW2RGobymcAIsNjk1gDFA9w8opAbg8z/ax/HdEQJd5COLGbeCXRkS+8cgY7SxXsAgpuUbS5XSZhWtcsr8HubwV4FkyTg8nTe1WPxIpl6llCTzDjPOCN5iCFbDDtdi9JMn5ysDMkRAx71Axj6+cSjRFT5mVCczyb2IZbec/0IKN17sYcRf3ZaXGS3J18QUkgIolhBK/myazTCNjuAEYo13UP9UmF9fLV0HfKadOHRe9iymGcTYfrpP4BiQRa9c/5TbyyqnbUfUUVwj7TCcBHDzqs8qQwuLhE7iuxGQtHYFbTJrt6G3uvoL+bXRHfxcArwoJT5aW6I7DgvmFsNSemtPrVTDTNXMcuJ7ULPJhrGXEVNgDyDNml3r0jZAZNiE6SwvMoofw+Vt3HvboRcPfqUBu5K0z7tKTUQM38Y3AD7sb0xlIws/xXEmmD31lBC7hzySROmHciZHMfX6nHT54Ne66/jp48cpf8gsW1eaeg6cG9FMwE2HqqPtkAWp+c9JHKa3dPYgvzU+FIE3v7BUPM6F3FoL/bq8sCONF4QH8TF9LyIeScUVEZToKy6tmEGbT6oHokRXQSf9mc3ZUEzVsaWzkTkn2XlzDfmuYdgecvFLqy7cQj0TKi8Tn1+PduuUolpB1wPMyuKniYc6/YEb1BR//F51EburURGITW4gTVclEvfDXjucUySzAe+tahQJVoBfq5M/wOVZgxOgT60mil06cVj78jIPNkeYbH57n5sPZHdGIwZZBAdhL5c0CHre9kOUpxNtYlNlFNsjyI16rQ/kS1YykgIY6AmBHwqqb39FKeDl/EisCNrLMDbVBfu0O7HmJAM78xxRscXGjZwVsr0JmGeNjS8Ndb3VcaSJTOkPE38f0C0Y5Z2rSkMDfYMHt7HDzQ4BD8cvFN3hZVIy+EoGLHOxleh4gtQvuS8TpbfDrNg94UwwY0KWgSZJ/ZTc0QdqAIq1+D3mSuWXd+Tq3IYX9aLdry7LtXDrA1LOuAZI44uFsP4Vv1ogMbXWqzCsnhaKoL+zbGUbTmsS7TEwK7aElKzzfvW/9miFNwQqtYqCvzuzHkhLtHN8mdznbQ6acpcg3pEyDlToMH1cAQ0Ma3wwk45R64Y6AJASs,iv:c+YDZfQnJqdEmVJo8ocfmz9qSAUGJIiCgR6rrPhkDlM=,tag:0/e2HSxSwQxMdi+2Dyx9rw==,type:str]
sops:
  age:
    - recipient: age1mq6usjzvvxvcp7tl03yjdqd0kgjhhvhz48kmg86p43nhx0jc75jssw0kfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbVAxOU9EekpINmVDbmg4
        aGM4aGlpbkVzNVp3akFwdGtCVllvbzNVOFNzCmVmUG85OTBiMFY3b05kNzFrd0kv
        UWJNLzlpWmQ5enNBa1dHVXo3dTdQZk0KLS0tIHVoWTF1cm1oUXRhRWZiQmtqYnc1
        WU50WnI0K0oyeDJTek9JY2ozZVR6aHcKhO6jXhMH04+g97aVYqGhpNW/0aMnfP84
        F9ibzn8HSYA4pzaMth16BhE6SSXZzGq8wYiyOYRasawS6EfaaT+LuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T17:08:07Z"
  mac: ENC[AES256_GCM,data:A4V58CbIin6h7K87gu8d5XFrhgE1+VNkGsbZw73Ok080Vd4jp1qInuBL47SIwO+KK9bne50GeAi5ECtnn+qmBRV24s4oEn1qblj5WAjarpim/Uj4171yj0i7GoHkhy43cSXF4tKl5DS6kCQHK0UlFJCgCkCnLcK7NqgdEVV+gaU=,iv:0RFXBrK6hnAcUONyTypZ/gSzhu2f1LsMVXV6xTdkd38=,tag:oKfvTpmjdznBV8V5xiMdYg==,type:str]
  encrypted_regex: ^(data|stringData|annotations|)$
  version: 3.11.0
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: webhook-config
  namespace: go-ddns-controller-system
data:
  config: ""
sops:
  age:
    - recipient: age1mq6usjzvvxvcp7tl03yjdqd0kgjhhvhz48kmg86p43nhx0jc75jssw0kfn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbVAxOU9EekpINmVDbmg4
        aGM4aGlpbkVzNVp3akFwdGtCVllvbzNVOFNzCmVmUG85OTBiMFY3b05kNzFrd0kv
        UWJNLzlpWmQ5enNBa1dHVXo3dTdQZk0KLS0tIHVoWTF1cm1oUXRhRWZiQmtqYnc1
        WU50WnI0K0oyeDJTek9JY2ozZVR6aHcKhO6jXhMH04+g97aVYqGhpNW/0aMnfP84
        F9ibzn8HSYA4pzaMth16BhE6SSXZzGq8wYiyOYRasawS6EfaaT+LuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T17:08:07Z"
  mac: ENC[AES256_GCM,data:A4V58CbIin6h7K87gu8d5XFrhgE1+VNkGsbZw73Ok080Vd4jp1qInuBL47SIwO+KK9bne50GeAi5ECtnn+qmBRV24s4oEn1qblj5WAjarpim/Uj4171yj0i7GoHkhy43cSXF4tKl5DS6kCQHK0UlFJCgCkCnLcK7NqgdEVV+gaU=,iv:0RFXBrK6hnAcUONyTypZ/gSzhu2f1LsMVXV6xTdkd38=,tag:oKfvTpmjdznBV8V5xiMdYg==,type:str]
  encrypted_regex: ^(data|stringData|annotations|)$
  version: 3.11.0
