---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ngf
  namespace: nginx-gateway
spec:
  interval: 1h
  install:
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: nginx-gateway-fabric
      version: 2.2.1
      interval: 1h
      sourceRef:
        kind: HelmRepository
        name: ngf
        namespace: flux-system
  values:
    nginxGateway:
      name: nginx-gateway
      image:
        repository: ghcr.io/nginx/nginx-gateway-fabric
        tag: 2.2.1
        pullPolicy: IfNotPresent
      productTelemetry:
        enable: false
    nginx:
      service:
        loadBalancerIP: 192.168.1.19
