---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: replacedby
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - gateway-api.yaml
  - database.yaml
  - secret.sops.yaml
