apiVersion: v1
kind: Service
metadata:
  name: replacedby
spec:
  selector:
    app.kubernetes.io/instance: replacedby
    app.kubernetes.io/name: replacedby
  ports:
    - name: web
      protocol: TCP
      port: 8080
