---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: changedetection-internal
    namespace: {{ $.Release.Namespace }}
    annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Monitors changes to websites
        gethomepage.dev/group: Automation
        gethomepage.dev/icon: changedetection-io
        gethomepage.dev/name: ChangeDetection.io
        gethomepage.dev/widget.type: changedetectionio
        gethomepage.dev/widget.url: https://changedetection.sgenov.dev
        gethomepage.dev/widget.key: 24f82bd47ffef64b0b533239ad38d945 # yeah, it's public, but it's not so secret
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "changedetection.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: changedetection
      port: {{ .Values.changedetection.port }}
