apiVersion: v1
kind: Service
metadata:
  name: kapowarr
spec:
  selector:
    app.kubernetes.io/instance: kapowarr
    app.kubernetes.io/name: kapowarr
  ports:
    - name: web
      protocol: TCP
      port: 8084
