---
syncthing:
    image: lscr.io/linuxserver/syncthing:2.0.14
    replicas: 1
    port: 8384
    resources:
        requests:
            cpu: 10m
            memory: 50Mi

storage:
    syncthingConfigSize: 1Gi
    nasIp: 192.168.1.39
