apiVersion: v2
appVersion: 1.0.0
description: This chart is used to install uptimekuma
maintainers:
- email: sgenov94@gmail.com
  name: Stefan Genov
name: uptimekuma
type: application
version: 1.0.0
