---
{{- with .Values.rss }}

apiVersion: v1
kind: ConfigMap
metadata:
    name: rss-config
    namespace: {{ $.Release.Namespace }}
data:
    feeds.txt: |
        https://noted.lol/rss Noted‚≠ê[#9233B1] #self-hosting
        https://feeds.fireside.fm/selfhosted/rss Linux-Server[#0078b9] #self-hosting

{{- end }}
