# ---
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#     name: firefly-external
#     namespace: {{ $.Release.Namespace }}
# spec:
#   parentRefs:
#   - name: external
#     namespace: istio-gateway
#   hostnames:
#     - "firefly.sgenov.dev"
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: /
#     backendRefs:
#     - name: firefly
#       port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: firefly-internal
    namespace: {{ $.Release.Namespace }}
spec:
  parentRefs:
  - name: internal
    namespace: istio-gateway
  hostnames:
    - "firefly.sgenov.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: firefly
      port: 80
