---
mealie:
  replicas: 1
  image: ghcr.io/mealie-recipes/mealie:v3.11.0
  port: 9000
  baseUrl: https://mealie.sgenov.dev
  resources:
    requests:
      cpu: 10m
      memory: 50Mi

storage:
  dataSize: 2Gi
