---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - k8s-at-home
    - metrics-server
    - unofficial
    - longhorn-system
    - cert-manager
    - ingress-nginx
    - reflector
    - velero
    - botkube
    - kube-vip
