---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aqua
  - cnpg
  - observability
  - k8s-at-home
  - metrics-server
  - unofficial
  - longhorn-system
  - cert-manager
  - reflector
  - velero
  - kube-vip
  - kyverno
  - kubereboot
  - descheduler
  - gabe565
  - go-ddns-controller
  - metallb
  - tika
  - maikumori
  - mariadb-operator
  - bjw-s
  - wger
  - istio
  - tofu-controller
