apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-replacedby
  namespace: istio-gateway
spec:
  addresses:
    - type: IPAddress
      value: 192.168.1.17
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      hostname: "replacedby.net"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: replacedby-cert
      allowedRoutes:
        namespaces:
          from: All
