apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  namespace: istio-gateway
spec:
  addresses:
    - type: IPAddress
      value: 192.168.1.15
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
    - name: https
      hostname: "*.sgenov.dev"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: ingress
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              # For internal, allow from anywhere
              from: All
