---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - internal-gateway.yaml
  - external-gateway.yaml
  - external-gateway-adygenova.yaml
  - external-gateway-replacedby.yaml
  - namespace.yaml
