apiVersion: velero.io/v1
kind: Schedule
metadata:
    name: general
    namespace: velero
spec:
    schedule: '00 03 * * *'
    template:
        hooks: {}
        includedNamespaces:
          - nodered
          - changedetection
          - mealie
          - media
          - monitoring
          - uptimekuma
          - freshrss
        snapshotVolumes: true
        ttl: 96h0m0s
    useOwnerReferencesInBackup: false
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
    name: sensitive
    namespace: velero
spec:
    schedule: '00 04 * * *'
    template:
        hooks: {}
        includedNamespaces:
          - postgresql
        snapshotVolumes: true
        ttl: 168h0m0s
    useOwnerReferencesInBackup: false
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
    name: critical
    namespace: velero
spec:
    schedule: '00 05 * * *'
    template:
        hooks: {}
        includedNamespaces:
          - vaultwarden
        snapshotVolumes: true
        ttl: 720h0m0s
    useOwnerReferencesInBackup: false 
